version: '3'

services:
  api:
    image: danielgtaylor/apisprout
    volumes:
    - ./api/openapi.yaml:/openapi.yaml
    command:
    - /openapi.yaml
    - --watch
    - --add-server
    - http://api:8000/api/
    - --validate-server

  ui:
    build:
      context: ./ui
    volumes:
    - .:/workspace
    - ~/.ssh:/root/.ssh
    ports:
    - 3000:3000