version: '2.1'
jobs:
  test:
    docker:
    - image: node:lts-slim
    environment:
      ENV: CI
    working_directory: ~/project/ui
    steps:
    - checkout
        working_directory: ~/project
    - run:
        command: |
          pwd
          ls
          yarn
    - run:
        command: |
          yarn test
workflows:
  version: 2
  test:
    jobs:
    - test