version: '2.1'
orbs:
  cypress: cypress-io/cypress@1
jobs:
  test:
    docker:
    - image: node:lts-slim
    environment:
      ENV: CI
    working_directory: ~/project/ui
    steps:
    - checkout:
        path: ~/project
    - run:
        command: yarn
    - run:
        command: yarn test
workflows:
  version: 2
  test:
    jobs:
    - test
    - cypress/run