version: '2.1'
jobs:
  test:
    docker:
    - image: node:lts-slim
    environment:
      ENV: CI
    working_directory: ui/
    steps:
    - checkout
    - run:
      command:
        yarn
    - run:
      command:
        yarn test
workflows:
  version: 2
  test:
    jobs:
    - test